# Generated by Django 5.2.7 on 2026-03-28 20:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="about",
            field=ckeditor.fields.RichTextField(default="default about text"),
            preserve_default=False,
        ),
    ]
