# Generated by Django 5.2.7 on 2026-03-29 21:37

import app_main.models.company
import app_main.models.service
import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("company_about", ckeditor.fields.RichTextField()),
                ("company_location", models.CharField(max_length=255)),
                ("company_year_founded", models.DateField()),
                ("company_industry", models.CharField(max_length=255)),
                ("company_email", models.EmailField(max_length=254)),
                ("company_phone", models.CharField(max_length=13)),
                (
                    "company_size",
                    models.CharField(
                        choices=[
                            ("1-20", "1-20"),
                            ("20-50", "20-50"),
                            ("50-100", "50-100"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "company_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=app_main.models.company.company_image_upload_path,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="companies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Freelancer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("freelancer_about", ckeditor.fields.RichTextField()),
                ("freelancer_location", models.CharField(max_length=255)),
                ("freelancer_industry", models.CharField(max_length=255)),
                ("freelancer_phone", models.CharField(max_length=13)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="freelancer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Links",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("website", "Website"),
                            ("linkedin", "LinkedIn"),
                            ("x", "X"),
                            ("instagram", "Instagram"),
                            ("facebook", "Facebook"),
                            ("github", "Github"),
                        ],
                        max_length=50,
                    ),
                ),
                ("address", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_title", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=100)),
                ("service_description", ckeditor.fields.RichTextField()),
                (
                    "service_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=app_main.models.service.service_image_upload_to,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
