# Generated by Django 5.2.7 on 2026-03-24 19:17

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("company_about", ckeditor.fields.RichTextField()),
                ("company_location", models.CharField(max_length=255)),
                ("company_year_founded", models.PositiveIntegerField()),
                ("company_industry", models.CharField(max_length=255)),
                ("company_email", models.EmailField(max_length=254)),
                ("company_phone", models.CharField(max_length=13)),
                (
                    "company_size",
                    models.CharField(
                        choices=[
                            ("1-20", "1-20"),
                            ("20-50", "20-50"),
                            ("50-100", "50-100"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="companies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
