# Generated by Django 5.2.7 on 2026-03-29 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServicePackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "package_type",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("standard", "Standard"),
                            ("premium", "Premium"),
                        ],
                        max_length=20,
                    ),
                ),
                ("package_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("package_desc", models.TextField()),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packages",
                        to="app_main.service",
                    ),
                ),
            ],
            options={
                "unique_together": {("service", "package_type")},
            },
        ),
    ]
