# Generated by Django 5.2.7 on 2026-03-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="company_year_founded",
            field=models.DateField(),
        ),
    ]
