# Generated by Django 5.2.7 on 2026-03-25 16:44

import app_main.models.company
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_main", "0002_alter_company_company_year_founded"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="company_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=app_main.models.company.company_image_upload_path,
            ),
        ),
    ]
