# Generated by Django 5.2.7 on 2026-03-25 18:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_main", "0004_link"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Link",
            new_name="Links",
        ),
    ]
