# Generated by Django 5.2.7 on 2026-03-29 07:24

import app_main.models.service
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_main", "0007_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="service_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=app_main.models.service.service_image_upload_to,
            ),
        ),
    ]
