# Generated by Django 5.2.7 on 2026-03-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_main", "0008_alter_service_service_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="User",
            new_name="user",
        ),
        migrations.AddField(
            model_name="service",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
