# Generated by Django 5.2.7 on 2026-03-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_main", "0009_rename_user_service_user_service_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
